# Generated by Django 6.0 on 2025-12-04 16:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Nome do Cargo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Equipe')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_admissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Admissão')),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salário Base')),
                ('descontar_vale_transporte', models.BooleanField(default=False, verbose_name='Descontar Vale Transporte (6%)')),
                ('valor_plano_saude', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Plano de Saúde')),
                ('outros_descontos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Outros Descontos')),
                ('jornada_entrada', models.TimeField(default='08:00')),
                ('jornada_saida', models.TimeField(default='17:00')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_rh.cargo', verbose_name='Cargo')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_rh.equipe', verbose_name='Equipe / Setor')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lider_de', to='core_rh.funcionario', verbose_name='Gestor Responsável'),
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('entrada', models.TimeField(blank=True, null=True)),
                ('saida', models.TimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('arquivo_anexo', models.FileField(blank=True, null=True, upload_to='atestados/')),
                ('assinado_funcionario', models.BooleanField(default=False)),
                ('assinado_gestor', models.BooleanField(default=False)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_rh.funcionario')),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Folhas de Ponto',
                'unique_together': {('funcionario', 'data')},
            },
        ),
    ]
