# Generated by Django 6.0 on 2025-12-04 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='descontar_vale_transporte',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='outros_descontos',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='salario',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='valor_plano_saude',
        ),
    ]
