# Generated by Django 6.0 on 2025-12-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0002_remove_funcionario_descontar_vale_transporte_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroponto',
            options={'ordering': ['data'], 'verbose_name': 'Registro de Ponto', 'verbose_name_plural': 'Folhas de Ponto'},
        ),
        migrations.RemoveField(
            model_name='registroponto',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='registroponto',
            name='saida',
        ),
        migrations.AddField(
            model_name='equipe',
            name='local_trabalho',
            field=models.CharField(default='Matriz', help_text='Ex: Brasília-DF', max_length=100, verbose_name='Local de Trabalho'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='intervalo_padrao',
            field=models.CharField(default='13:00 às 14:12', max_length=50, verbose_name='Intervalo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='numero_contrato',
            field=models.CharField(blank=True, help_text='Ex: 11336/2022', max_length=20, null=True, verbose_name='Nº do Contrato'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='entrada_manha',
            field=models.TimeField(blank=True, null=True, verbose_name='Entrada'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='extra_entrada',
            field=models.TimeField(blank=True, null=True, verbose_name='Extra Entrada'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='extra_saida',
            field=models.TimeField(blank=True, null=True, verbose_name='Extra Saída'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='saida_almoco',
            field=models.TimeField(blank=True, null=True, verbose_name='Saída Almoço'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='saida_tarde',
            field=models.TimeField(blank=True, null=True, verbose_name='Saída'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='volta_almoco',
            field=models.TimeField(blank=True, null=True, verbose_name='Volta Almoço'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='jornada_entrada',
            field=models.TimeField(default='08:00', verbose_name='Entrada Padrão'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='jornada_saida',
            field=models.TimeField(default='18:00', verbose_name='Saída Padrão'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observação / Faltas'),
        ),
    ]
