# Generated by Django 6.0 on 2025-12-08 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0003_alter_registroponto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='outras_equipes',
            field=models.ManyToManyField(blank=True, related_name='funcionarios_secundarios', to='core_rh.equipe', verbose_name='Outras Equipes (Secundárias)'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_rh.equipe', verbose_name='Equipe Principal'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº do Contrato'),
        ),
    ]
