# Generated by Django 6.0 on 2025-12-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0004_funcionario_outras_equipes_alter_funcionario_equipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroponto',
            name='arquivo_anexo',
            field=models.FileField(blank=True, null=True, upload_to='ponto_assinado/'),
        ),
    ]
