# Generated by Django 6.0 on 2025-12-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0005_alter_registroponto_arquivo_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='local_trabalho_estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Local de Trabalho (Estado)'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='primeiro_acesso',
            field=models.BooleanField(default=True, verbose_name='Exigir troca de senha?'),
        ),
    ]
