# Generated by Django 6.0 on 2025-12-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0007_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='gestor',
        ),
        migrations.AddField(
            model_name='equipe',
            name='gestores',
            field=models.ManyToManyField(blank=True, related_name='equipes_lideradas', to='core_rh.funcionario', verbose_name='Gestores Responsáveis'),
        ),
    ]
