# Generated by Django 6.0 on 2025-12-17 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0008_remove_equipe_gestor_equipe_gestores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_aquisitivo', models.CharField(help_text='Ex: 2023/2024', max_length=50, verbose_name='Período Aquisitivo')),
                ('data_inicio', models.DateField(verbose_name='Início das Férias')),
                ('data_fim', models.DateField(verbose_name='Fim das Férias')),
                ('arquivo_aviso', models.FileField(blank=True, null=True, upload_to='ferias/avisos_originais/', verbose_name='Aviso de Férias (Para Assinar)')),
                ('arquivo_recibo', models.FileField(blank=True, null=True, upload_to='ferias/recibos_originais/', verbose_name='Recibo de Férias (Para Assinar)')),
                ('aviso_assinado', models.FileField(blank=True, null=True, upload_to='ferias/avisos_assinados/', verbose_name='Aviso Assinado (Pelo Colaborador)')),
                ('recibo_assinado', models.FileField(blank=True, null=True, upload_to='ferias/recibos_assinados/', verbose_name='Recibo Assinado (Pelo Colaborador)')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Enviado', 'Enviado ao RH'), ('Concluido', 'Concluído')], default='Pendente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_rh.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Férias',
                'verbose_name_plural': 'Controle de Férias',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
