# Generated by Django 6.0 on 2025-12-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rh', '0009_ferias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ferias',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Agendamento de Férias', 'verbose_name_plural': 'Gestão de Férias'},
        ),
        migrations.AddField(
            model_name='ferias',
            name='abono_pecuniario',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Abono Pecuniário'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='carteira_trabalho',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Carteira de Trabalho (CTPS)'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='registro_geral',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº Registro (Livro/Ficha)'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='serie_ctps',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='arquivo_aviso',
            field=models.FileField(blank=True, help_text='Gere o arquivo no Passo 2 e anexe aqui.', null=True, upload_to='ferias/avisos_originais/', verbose_name='Aviso de Férias (Original)'),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='arquivo_recibo',
            field=models.FileField(blank=True, null=True, upload_to='ferias/recibos_originais/', verbose_name='Recibo de Férias (Original)'),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='data_fim',
            field=models.DateField(verbose_name='Fim das Férias (Retorno)'),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='data_inicio',
            field=models.DateField(verbose_name='Início das Férias (Saída)'),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='periodo_aquisitivo',
            field=models.CharField(help_text='Ex: 2024/2025', max_length=50, verbose_name='Período Aquisitivo'),
        ),
    ]
